#!/usr/bin/env bash
# Cut over recovered legacy GitHub runner system services to the portable
# user-systemd units generated by scripts/install-runner-services.sh.
set -euo pipefail

runner_user="${FXRUN_RUNNER_USER:-flexnetos}"
prefix="${FXRUN_RUNNER_PREFIX:-/home/flexnetos/FlexNetOS/src/flexnetos_runner}"
unit_prefix="${FXRUN_RUNNER_UNIT_PREFIX:-flexnetos-runner}"
wait_seconds="${FXRUN_RUNNER_CUTOVER_WAIT_SECONDS:-600}"
force="${FXRUN_RUNNER_CUTOVER_FORCE:-0}"
drain_after_stop_seconds="${FXRUN_RUNNER_CUTOVER_DRAIN_AFTER_STOP_SECONDS:-${wait_seconds}}"
legacy_units=(
  actions.runner.FlexNetOS.fxrun-drdave-TRX50-AI-TOP-flexnetos-01.service
  actions.runner.FlexNetOS.fxrun-drdave-TRX50-AI-TOP-flexnetos-02.service
)
portable_units=(
  "${unit_prefix}@01.service"
  "${unit_prefix}@02.service"
)

if [[ "${EUID}" -ne 0 ]]; then
  echo "run with sudo/root so the legacy system services can be stopped safely" >&2
  exit 1
fi

user_home="$(getent passwd "${runner_user}" | awk -F: '{print $6}')"
if [[ -z "${user_home}" ]]; then
  echo "could not resolve home for ${runner_user}" >&2
  exit 1
fi
unit_file="${user_home}/.config/systemd/user/${unit_prefix}@.service"
if [[ ! -f "${unit_file}" ]]; then
  echo "portable user unit is missing: ${unit_file}" >&2
  echo "run scripts/install-runner-services.sh --prefix ${prefix} --mode user --apply --no-enable first" >&2
  exit 1
fi

loginctl enable-linger "${runner_user}"
uid="$(id -u "${runner_user}")"
user_systemctl=(
  runuser -u "${runner_user}" --
  env "XDG_RUNTIME_DIR=/run/user/${uid}" "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${uid}/bus"
  systemctl --user
)

echo "stopping legacy system runner listeners so they stop accepting new jobs..." >&2
systemctl stop --no-block "${legacy_units[@]}"

if [[ "${force}" == 1 ]]; then
  echo "force cutover requested; terminating any remaining legacy runner listener/worker processes" >&2
  pkill -TERM -u "${runner_user}" -f "${prefix}/_work/repos/actions-runner-(01|02)/bin/Runner.(Listener|Worker)" || true
  sleep 3
  pkill -KILL -u "${runner_user}" -f "${prefix}/_work/repos/actions-runner-(01|02)/bin/Runner.(Listener|Worker)" || true
else
  deadline=$((SECONDS + drain_after_stop_seconds))
  while pgrep -u "${runner_user}" -f "${prefix}/_work/repos/actions-runner-(01|02)/bin/Runner.(Listener|Worker)" >/dev/null; do
    if (( SECONDS >= deadline )); then
      echo "legacy runner processes did not drain within ${drain_after_stop_seconds}s after stop request; set FXRUN_RUNNER_CUTOVER_FORCE=1 to terminate them" >&2
      pgrep -u "${runner_user}" -af "${prefix}/_work/repos/actions-runner-(01|02)/bin/Runner.(Listener|Worker)" >&2 || true
      exit 1
    fi
    echo "waiting for legacy listener/workers to drain after stop request..." >&2
    sleep 2
  done
fi

systemctl disable "${legacy_units[@]}"

"${user_systemctl[@]}" daemon-reload
"${user_systemctl[@]}" enable --now "${portable_units[@]}"

systemctl show "${legacy_units[@]}" --property=Id,ActiveState,SubState,UnitFileState --no-pager || true
"${user_systemctl[@]}" show "${portable_units[@]}" \
  --property=Id,LoadState,ActiveState,SubState,FragmentPath,ExecStart,WorkingDirectory,Environment \
  --no-pager
